on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/react-native-android-nx@v2
      - name: Get the output time
        run: echo "The time was done"
