on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: aslamanver/react-native-docker@1.0.1
      - name: Get the output time
        run: echo "The time was done"
